export const domElements = {
    container : document.querySelector('.container'),
    postsList: document.querySelector('.posts__list'),
    searchInput: document.querySelector('.search__input'), 
    searchButton: document.querySelector('.btn__search'),
    createButton: document.querySelector('.btn__create'),
    popup: document.querySelector('.popup__modal'),
    closePopupButton: document.querySelector('.btn__close-pop'),
    addPostButton: document.querySelector('.btn__submit'),
    title: document.querySelector('.popup__title-input'),
    comment: document.querySelector('.popup__post-input'),
    readMoreButton: document.querySelector('.btn__post-details'),
    error: document.querySelector('.error'),
    loadMorePosts: document.querySelector('.btn__more-posts'),
}